.PHONY: clean All

All:
	@echo "----------Building project:[ PicEdit - Debug ]----------"
	@"$(MAKE)" -f  "PicEdit.mk"
clean:
	@echo "----------Cleaning project:[ PicEdit - Debug ]----------"
	@"$(MAKE)" -f  "PicEdit.mk" clean
